#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["src/Comments/Hosts/CommentAPI/Comments.API.csproj", "src/Comments/Hosts/CommentAPI/"]
COPY ["src/Comments/Infrastructure/Mapper/Comments.Mapper.csproj", "src/Comments/Infrastructure/Mapper/"]
COPY ["src/Comments/Domain/Comments.Domain.csproj", "src/Comments/Domain/"]
COPY ["src/Comments/Contracts/Comments.Contracts.csproj", "src/Comments/Contracts/"]
COPY ["src/Comments/Infrastructure/CommentMigrations/Comments.Migrations.csproj", "src/Comments/Infrastructure/CommentMigrations/"]
COPY ["src/Comments/Infrastructure/Repository/Comments.Repository.csproj", "src/Comments/Infrastructure/Repository/"]
COPY ["src/Comments/Application/CommentService/Comments.Services.csproj", "src/Comments/Application/CommentService/"]
RUN dotnet restore "src/Comments/Hosts/CommentAPI/Comments.API.csproj"
COPY . .
WORKDIR "/src/src/Comments/Hosts/CommentAPI"
RUN dotnet build "Comments.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Comments.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Comments.API.dll"]