version: "3"

services:
  accounts:
    image: skarfe/accounts
    build: src/Accounts/
    ports:
      - 49171:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  advertisements:
    image: skarfe/advertisements
    build: src/Advertisements/
    ports:
      - 49172:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  comments:
    image: skarfe/comments
    build: src/Comments/
    ports:
      - 49173:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notificationsemail:
    image: skarfe/notificationsemail
    build: src/NotificationsEmail/
    ports:
      - 49174:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ui:
    image: skarfe/ui
    build: UI
    ports:
      - 80:80