version: "3"

services:
  accounts:
    image: skarfe/accounts
    build:
        context: ./
        dockerfile: Dockerfile_Accounts
    ports:
      - 44377:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  advertisements:
    image: skarfe/advertisements
    build:
        context: ./
        dockerfile: Dockerfile_Advertisements
    ports:
      - 44378:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  comments:
    image: skarfe/comments
    build:
        context: ./
        dockerfile: Dockerfile_Comments
    ports:
      - 49173:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notificationsemail:
    image: skarfe/notificationsemail
    build:
        context: ./
        dockerfile: Dockerfile_NotificationsEmail
    ports:
      - 5003:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  eventbus:
    image: skarfe/eventbus
    build:
        context: ./
        dockerfile: Dockerfile_EventBus
    ports:
      - 49172:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  userfiles:
    image: skarfe/userfiles
    build:
        context: ./
        dockerfile: Dockerfile_UserFiles
    ports:
      - 44379:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ui:
    image: skarfe/ui
    build:
        context: ./
        dockerfile: Dockerfile_UI2
    ports:
      - 80:80