version: "3.7"

##############################################################
##############################################################
## Services
##############################################################
##############################################################

services: 

  ##############################################################
  # Redis
  # https://cloudinfrastructureservices.co.uk/run-redis-with-docker-compose/
  ##############################################################

  redis:
    image: 'bitnami/redis:7.0.7'
    volumes:
      - '/c/Docker/BulletingBoard/Redis:/bitnami/redis/data'
    networks:
      - app-network  
    environment:
      - REDIS_PASSWORD=password123
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    restart: always
