version: '3.4'

##############################################################
##############################################################
## Services
##############################################################
##############################################################

services:


  ##############################################################
  # Accounts
  ##############################################################
  
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    #restart: always
    build:
      context: .
      dockerfile: src/Accounts/Hosts/Accounts.Api/Dockerfile
    depends_on:
      accounts.postgres:
        condition: service_healthy
    networks:
      - app-network  
        
  accounts.postgres:
    image: "postgres:15.1"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network  

  accounts.redis:
    image: 'bitnami/redis:7.0.7'
    restart: always
    networks:
      - app-network  


  ##############################################################
  # Advertisements
  ##############################################################
  
  advertisements.api:
    image: ${DOCKER_REGISTRY-}advertisementsapi
    restart: always
    build:
      context: .
      dockerfile: src/Advertisements/Hosts/Advertisements.Api/Dockerfile
    depends_on:
      advertisements.postgres:
        condition: service_healthy
    networks:
      - app-network  
        
  advertisements.postgres:
    image: "postgres:15.1"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network  


  ##############################################################
  # UserFiles
  ##############################################################
  
  user_files.api:
    image: ${DOCKER_REGISTRY-}userfilesapi
    restart: always
    build:
      context: .
      dockerfile: src/UserFiles/Hosts/UserFiles.Api/Dockerfile
    depends_on:
      user_files.postgres:
        condition: service_healthy
    networks:
      - app-network  
        
  user_files.postgres:
    image: "postgres:15.1"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network  


##############################################################
##############################################################
## Networks
##############################################################
##############################################################

networks:
  app-network:
    driver: bridge
    external: true
    
#networks:
  #default:
    #name: dev_network
    #external: true
    #driver: bridge