FROM node:14.18.1 as build
WORKDIR /usr/src/app
COPY UI/package.json UI/package-lock.json ./
RUN npm install
COPY UI/ .
RUN npm run build

FROM nginx
COPY UI/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/my-app /usr/share/nginx/html