version: '3.4'

##############################################################
##############################################################
## Services
##############################################################
##############################################################
services:

  ##############################################################
  # Accounts
  ##############################################################
  
  accounts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "49001:80"
      - "44301:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
  accounts.postgres:
    environment:
        - POSTGRES_DB=accounts_db
        - POSTGRES_USER=accounts_user
        - POSTGRES_PASSWORD=#V6G&W%2OB6H
    ports: 
        - "49021:5432"
    volumes:
        - accounts_data:/mnt/largedb


  ##############################################################
  # Advertisements
  ##############################################################
  
  advertisements.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "49002:80"
      - "44302:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  advertisements.postgres:
    environment:
        - POSTGRES_DB=advertisements_db
        - POSTGRES_USER=advertisements_user
        - POSTGRES_PASSWORD=1BI(R5#bz*yT
    ports: 
        - "49022:5432"
    volumes:
        - advertisements_data:/mnt/largedb

  ##############################################################
  # UserFiles
  ##############################################################
  
  user_files.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "49003:80"
      - "44303:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  user_files.postgres:
    environment:
        - POSTGRES_DB=user_files_db
        - POSTGRES_USER=user_files_user
        - POSTGRES_PASSWORD=5t6k%%4ovq&u
    ports: 
        - "49023:5432"
    volumes:
        - user_files_data:/mnt/largedb


##############################################################
##############################################################
## Volumes
##############################################################
##############################################################   
volumes:

  accounts_data:
    driver_opts:
      type: none
      device: /c/Docker/Root/BulletingBoard/Postgres/Accounts/largedb
      o: bind

  advertisements_data:
    driver_opts:
      type: none
      device: /c/Docker/Root/BulletingBoard/Postgres/Advertisements/largedb
      o: bind

  user_files_data:
    driver_opts:
      type: none
      device: /c/Docker/Root/BulletingBoard/Postgres/UserFiles/largedb
      o: bind