version: "3"

services:
  accounts:
    image: skarfe/accounts
    build:
        context: ./
        dockerfile: Dockerfile_Accounts
    ports:
      - 49171:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  advertisements:
    image: skarfe/advertisements
    build:
        context: ./
        dockerfile: Dockerfile_Advertisements
    ports:
      - 49172:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  comments:
    image: skarfe/comments
    build:
        context: ./
        dockerfile: Dockerfile_Comments
    ports:
      - 49173:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notificationsemail:
    image: skarfe/notificationsemail
    build:
        context: ./
        dockerfile: Dockerfile_NotificationsEmail
    ports:
      - 49174:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ui:
    image: skarfe/ui
    build:
        context: ./
        dockerfile: Dockerfile_UI
    ports:
      - 80:80