version: '3.4'

##############################################################
##############################################################
## Services
##############################################################
##############################################################
services:

  ##############################################################
  # Accounts
  ##############################################################
  
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: src/Accounts/Hosts/Accounts.Api/Dockerfile

  accounts.postgres:
    image: "postgres:15.1"
    restart: always


  ##############################################################
  # Advertisements
  ##############################################################
  
  advertisements.api:
    image: ${DOCKER_REGISTRY-}advertisementsapi
    build:
      context: .
      dockerfile: src/Advertisements/Hosts/Advertisements.Api/Dockerfile
      
  advertisements.postgres:
    image: "postgres:15.1"
    restart: always


  ##############################################################
  # UserFiles
  ##############################################################
  
  user_files.api:
    image: ${DOCKER_REGISTRY-}userfilesapi
    build:
      context: .
      dockerfile: src/UserFiles/Hosts/UserFiles.Api/Dockerfile

  user_files.postgres:
    image: "postgres:15.1"
    restart: always
