version: '3.4'

services:
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: src/Accounts/Hosts/Accounts.Api/Dockerfile

  advertisements.api:
    image: ${DOCKER_REGISTRY-}advertisementsapi
    build:
      context: .
      dockerfile: src/Advertisements/Hosts/Advertisements.Api/Dockerfile


  userfiles.api:
    image: ${DOCKER_REGISTRY-}userfilesapi
    build:
      context: .
      dockerfile: src/UserFiles/Hosts/UserFiles.Api/Dockerfile

