version: "3.7"

# Sercives only!

# First time: run "_docker_compose_create_volumes.cmd"!!!

services: 

  ##############################################################
  # Accounts
  ##############################################################

  bulleting_board-services-accounts:
    build:
        context: ./
        dockerfile: ./src/Accounts/Hosts/Accounts.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44301:80"
      - "443" 


  ##############################################################
  # Advertisements
  ##############################################################

  bulleting_board-services-advertisements:
    image: myrsaitov/bulleting_board-advertisements
    build:
        context: ./
        dockerfile: ./src/Advertisements/Hosts/Advertisements.Api/Dockerfile
    ports:
      - "44302:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

   
  ##############################################################
  # UserFiles
  ##############################################################

  bulleting_board-services-user_files:
    image: myrsaitov/bulleting_board-user_files
    build:
        context: ./
        dockerfile: ./src/UserFiles/Hosts/UserFiles.Api/Dockerfile
    ports:
      - "44303:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
