version: '3.4'

##############################################################
##############################################################
## Networks
##############################################################
##############################################################

networks:

  app-network:
    driver: bridge
    external: true
    
#networks:
  #default:
    #name: dev_network
    #external: true
    #driver: bridge
    