version: "3.7"

##############################################################
##############################################################
## Services
##############################################################
##############################################################

services: 

  ##############################################################
  # Redis
  # https://cloudinfrastructureservices.co.uk/run-redis-with-docker-compose/
  ##############################################################

  redis:
    image: "bitnami/redis:7.0.7"
    container_name: redis
    volumes:
      - ${REDIS_VOLUME_PATH}:/bitnami/redis/data
    networks:
      - app-network  
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
      - REDIS_PORT_NUMBER=${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    restart: always
