version: '3.4'

##############################################################
##############################################################
## Services
##############################################################
##############################################################

services:


  ##############################################################
  # Accounts
  ##############################################################
  
  accounts.api:
    build:
      context: ./../..
      args:
        MODE: Release
      dockerfile: ./docker-compose/configs/Dockerfile_Accounts
      labels:
        developer: "myrsaitov"


  ##############################################################
  # Advertisements
  ##############################################################
  
  advertisements.api:
    build:
      context: ./../..
      args:
        MODE: Release
      dockerfile: ./docker-compose/configs/Dockerfile_Advertisements
      labels:
        developer: "myrsaitov"
      

  ##############################################################
  # UserFiles
  ##############################################################
  
  user_files.api:
    build:
      context: ./../..
      args:
        MODE: Release
      dockerfile: ./docker-compose/configs/Dockerfile_UserFiles
      labels:
        developer: "myrsaitov"
