version: '3.4'

##############################################################
##############################################################
## Services
##############################################################
##############################################################

services:


  ##############################################################
  # Accounts
  ##############################################################
  
  accounts.api:
    image: bulleting_board/accounts.api
    container_name: accounts.api
    build:
      context: ./../..
      args:
        MODE: ${MODE}
      dockerfile: ./docker-compose/configs/Dockerfile_Accounts
      labels:
        developer: "myrsaitov"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/DataProtection-Keys:ro
    networks:
      - app-network  
    depends_on:
      accounts.postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always


  ##############################################################
  # Advertisements
  ##############################################################
  
  advertisements.api:
    image: bulleting_board/advertisements.api
    container_name: advertisements.api
    build:
      context: ./../..
      args:
        MODE: ${MODE}
      dockerfile: ./docker-compose/configs/Dockerfile_Advertisements
      labels:
        developer: "myrsaitov"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/DataProtection-Keys:ro
    networks:
      - app-network  
    depends_on:
      advertisements.postgres:
        condition: service_healthy
    restart: always
      

  ##############################################################
  # UserFiles
  ##############################################################
  
  user_files.api:
    image: bulleting_board/user_files.api
    container_name: user_files.api
    build:
      context: ./../..
      args:
        MODE: ${MODE}
      dockerfile: ./docker-compose/configs/Dockerfile_UserFiles
      labels:
        developer: "myrsaitov"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/DataProtection-Keys:ro
    networks:
      - app-network  
    depends_on:
      user_files.postgres:
        condition: service_healthy
    restart: always
