version: '3.4'

##############################################################
##############################################################
## Services
##############################################################
##############################################################

services:


  ##############################################################
  # Accounts
  ##############################################################
  
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: ./../..
      dockerfile: ./docker-compose/configs/Dockerfile_Accounts
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/DataProtection-Keys:ro
    networks:
      - app-network  
    depends_on:
      accounts.postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always


  ##############################################################
  # Advertisements
  ##############################################################
  
  advertisements.api:
    image: ${DOCKER_REGISTRY-}advertisementsapi
    build:
      context: ./../..
      dockerfile: ./docker-compose/configs/Dockerfile_Advertisements
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/DataProtection-Keys:ro
    networks:
      - app-network  
    depends_on:
      advertisements.postgres:
        condition: service_healthy
    restart: always
      

  ##############################################################
  # UserFiles
  ##############################################################
  
  user_files.api:
    image: ${DOCKER_REGISTRY-}userfilesapi
    build:
      context: ./../..
      dockerfile: ./docker-compose/configs/Dockerfile_UserFiles
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/DataProtection-Keys:ro
    networks:
      - app-network  
    depends_on:
      user_files.postgres:
        condition: service_healthy
    restart: always
