version: '3.4'

##############################################################
##############################################################
## Services
##############################################################
##############################################################

services:


  ##############################################################
  # Accounts
  ##############################################################
  
  accounts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ACTIVE_ENVIRONMENT}
      - ASPNETCORE_URLS=${HTTP_URLS}
      - ASPNETCORE_HTTPS_PORT=${PORT_SSL_ACCOUNTS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${KESTREL_CERTIFICATE_PATH}
      - AllowedHosts=${ALLOWED_HOSTS_ACCOUNTS}
      - Token__Key=${TOKEN_KEY_ACCOUNTS}
      - DataBaseOptions__UseMsSql=${USE_MSSQL}
      - ConnectionStrings__PostgresAccountsDb=${ACCOUNTS_POSTGRES_CONNECTION}
      - ConnectionStrings__MsSqlAccountsDb=${ACCOUNTS_MSSQL_CONNECTION}
      - ConnectionStrings__Redis=${REDIS_CONNECTION}
      - RegionValidateApiClientUri=${REGION_VALIDATE_API_CLIENT_URI}


  ##############################################################
  # Advertisements
  ##############################################################
  
  advertisements.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ACTIVE_ENVIRONMENT}
      - ASPNETCORE_URLS=${HTTP_URLS}
      - ASPNETCORE_HTTPS_PORT=${PORT_SSL_ADVERTISEMENTS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${KESTREL_CERTIFICATE_PATH}
      - AllowedHosts=${ALLOWED_HOSTS_ADVERTISEMENTS}
      - Token__Key=${TOKEN_KEY_ADVERTISEMENTS}
      - DataBaseOptions__UseMsSql=${USE_MSSQL}
      - ConnectionStrings__PostgresAdvertisementsDb=${ADVERTISEMENTS_POSTGRES_CONNECTION}
      - ConnectionStrings__MsSqlAdvertisementsDb=${ADVERTISEMENTS_MSSQL_CONNECTION}
      - UserValidateApiClientUri=${USER_VALIDATE_API_CLIENT_URI}
      - UserFilesUploadApiClientUri=${USER_FILES_UPLOAD_API_CLIENT_URI}


  ##############################################################
  # UserFiles
  ##############################################################
  
  user_files.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ACTIVE_ENVIRONMENT}
      - ASPNETCORE_URLS=${HTTP_URLS}
      - ASPNETCORE_HTTPS_PORT=${PORT_SSL_USER_FILES}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${KESTREL_CERTIFICATE_PATH}
      - AllowedHosts=${ALLOWED_HOSTS_USER_FILES}
      - Token__Key=${TOKEN_KEY_USER_FILES}
      - DataBaseOptions__UseMsSql=${USE_MSSQL}
      - ConnectionStrings__PostgresUserFilesDb=${USER_FILES_POSTGRES_CONNECTION}
      - ConnectionStrings__MsSqlUserFilesDb=${USER_FILES_MSSQL_CONNECTION}
      - UserValidateApiClientUri=${USER_VALIDATE_API_CLIENT_URI}
      - AdvertisementValidateApiClientUri=${ADVERTISEMENT_VALIDATE_API_CLIENT_URI}
      - UserFilesUploadApiClientUri=${USER_FILES_UPLOAD_API_CLIENT_URI}
      - YandexDisk__URI=${YANDEX_DISK_URI}
      - YandexDisk__BasePath=${YANDEX_DISK_BASE_PATH}
      - YandexDisk__OAuthValue=${YANDEX_DISK_OAUTH_VALUE}
