// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sev1.Advertisements.DataAccess;

namespace Advertisements.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211117233538_RegionsWereAdded")]
    partial class RegionsWereAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertisementTag", b =>
                {
                    b.Property<int>("AdvertisementsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("AdvertisementsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagAdvertisement");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Advertisement", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "299411 г. Москва, ул. Тургенева, 1",
                            Body = "Телевизор Xiaomi Mi TV 4S 50, 50, Ultra HD 4K",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(121),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 40000m,
                            RegionId = 1,
                            Status = 0,
                            Title = "Продам телевизор"
                        },
                        new
                        {
                            Id = 2,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(376),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 2000m,
                            RegionId = 2,
                            Status = 0,
                            Title = "Продам магнитофон"
                        },
                        new
                        {
                            Id = 3,
                            Address = "299713 г. Керчь, ул. Куприна, 3",
                            Body = "Телевизор Xiaomi Mi TV 4S 50, 50, Ultra HD 4K",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(380),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 40000m,
                            RegionId = 3,
                            Status = 0,
                            Title = "Телевизор"
                        },
                        new
                        {
                            Id = 4,
                            Address = "299314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(384),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 2000m,
                            RegionId = 4,
                            Status = 0,
                            Title = "Магнитофон"
                        },
                        new
                        {
                            Id = 5,
                            Address = "299415 г. Ялта, ул. Достоевского, 5",
                            Body = "Примитивные стиральные машины представляли собой деревянный ящик с подвижной рамой. Первая стиральная машина, запущенная в серийное производство, была создана в 1907 году[источник не указан 109 дней] Уильямом Блекстоуном, у неё был ручной привод (есть также мнение, что первую сделал Натаниэл Бриггс (Nathaniel Briggs)). В Европе первые стиральные машины начали производить в Германии в 1900 г. Современные машины с электрическим приводом появились в 1904 году[1]. Механизация труда практически привела к исчезновению профессии прачки. В 1949 году в США появилась первая автоматическая стиральная машина.",
                            CategoryId = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(386),
                            IsDeleted = false,
                            OwnerId = "7e24ccd2-34fd-4289-9a78-1aae93623bae",
                            Price = 10000m,
                            RegionId = 5,
                            Status = 0,
                            Title = "Стиральная машина"
                        },
                        new
                        {
                            Id = 6,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "Видеомагнитофо́н — устройство для записи телевизионного сигнала на магнитную ленту и его последующего воспроизведения[1][2]. От магнитофона отличается многократно увеличенной полосой записываемых частот и устройством лентопротяжного механизма[3]. Получаемая при помощи видеомагнитофона запись изображения и звука называется видеофонограммой[4][5]. Возможность записи высокочастотных и импульсных сигналов делает видеомагнитофон пригодным не только для видеозаписи, но и для других прикладных задач, связанных с регистрацией информации.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(388),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 40000m,
                            RegionId = 7,
                            Status = 0,
                            Title = "Видеомагнитофон"
                        },
                        new
                        {
                            Id = 7,
                            Address = "299713 г. Керчь, ул. Куприна, 3",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(390),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 2000m,
                            RegionId = 8,
                            Status = 0,
                            Title = "Куплю магнитофон"
                        },
                        new
                        {
                            Id = 8,
                            Address = "299314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Примитивные стиральные машины представляли собой деревянный ящик с подвижной рамой. Первая стиральная машина, запущенная в серийное производство, была создана в 1907 году[источник не указан 109 дней] Уильямом Блекстоуном, у неё был ручной привод (есть также мнение, что первую сделал Натаниэл Бриггс (Nathaniel Briggs)). В Европе первые стиральные машины начали производить в Германии в 1900 г. Современные машины с электрическим приводом появились в 1904 году[1]. Механизация труда практически привела к исчезновению профессии прачки. В 1949 году в США появилась первая автоматическая стиральная машина.",
                            CategoryId = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(391),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 2000m,
                            RegionId = 6,
                            Status = 0,
                            Title = "Стиральная машина"
                        },
                        new
                        {
                            Id = 9,
                            Address = "299411 г. Москва, ул. Тургенева, 1",
                            Body = "Телевизор Xiaomi Mi TV 4S 50, 50, Ultra HD 4K",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(392),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 40000m,
                            RegionId = 1,
                            Status = 0,
                            Title = "Продам телевизор"
                        },
                        new
                        {
                            Id = 10,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(394),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 2000m,
                            RegionId = 2,
                            Status = 0,
                            Title = "Продам магнитофон"
                        },
                        new
                        {
                            Id = 11,
                            Address = "299713 г. Керчь, ул. Куприна, 3",
                            Body = "Телевизор Xiaomi Mi TV 4S 50, 50, Ultra HD 4K",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(398),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 40000m,
                            RegionId = 3,
                            Status = 0,
                            Title = "Телевизор"
                        },
                        new
                        {
                            Id = 12,
                            Address = "299314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(399),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 2000m,
                            RegionId = 4,
                            Status = 0,
                            Title = "Магнитофон"
                        },
                        new
                        {
                            Id = 13,
                            Address = "299415 г. Ялта, ул. Достоевского, 5",
                            Body = "Примитивные стиральные машины представляли собой деревянный ящик с подвижной рамой. Первая стиральная машина, запущенная в серийное производство, была создана в 1907 году[источник не указан 109 дней] Уильямом Блекстоуном, у неё был ручной привод (есть также мнение, что первую сделал Натаниэл Бриггс (Nathaniel Briggs)). В Европе первые стиральные машины начали производить в Германии в 1900 г. Современные машины с электрическим приводом появились в 1904 году[1]. Механизация труда практически привела к исчезновению профессии прачки. В 1949 году в США появилась первая автоматическая стиральная машина.",
                            CategoryId = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(402),
                            IsDeleted = false,
                            OwnerId = "7e24ccd2-34fd-4289-9a78-1aae93623bae",
                            Price = 10000m,
                            RegionId = 5,
                            Status = 0,
                            Title = "Стиральная машина"
                        },
                        new
                        {
                            Id = 14,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "Видеомагнитофо́н — устройство для записи телевизионного сигнала на магнитную ленту и его последующего воспроизведения[1][2]. От магнитофона отличается многократно увеличенной полосой записываемых частот и устройством лентопротяжного механизма[3]. Получаемая при помощи видеомагнитофона запись изображения и звука называется видеофонограммой[4][5]. Возможность записи высокочастотных и импульсных сигналов делает видеомагнитофон пригодным не только для видеозаписи, но и для других прикладных задач, связанных с регистрацией информации.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(404),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 40000m,
                            RegionId = 7,
                            Status = 0,
                            Title = "Видеомагнитофон"
                        },
                        new
                        {
                            Id = 15,
                            Address = "299713 г. Керчь, ул. Куприна, 3",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(406),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 2000m,
                            RegionId = 8,
                            Status = 0,
                            Title = "Куплю магнитофон"
                        },
                        new
                        {
                            Id = 16,
                            Address = "299314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Примитивные стиральные машины представляли собой деревянный ящик с подвижной рамой. Первая стиральная машина, запущенная в серийное производство, была создана в 1907 году[источник не указан 109 дней] Уильямом Блекстоуном, у неё был ручной привод (есть также мнение, что первую сделал Натаниэл Бриггс (Nathaniel Briggs)). В Европе первые стиральные машины начали производить в Германии в 1900 г. Современные машины с электрическим приводом появились в 1904 году[1]. Механизация труда практически привела к исчезновению профессии прачки. В 1949 году в США появилась первая автоматическая стиральная машина.",
                            CategoryId = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(407),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 2000m,
                            RegionId = 6,
                            Status = 0,
                            Title = "Стиральная машина"
                        },
                        new
                        {
                            Id = 17,
                            Address = "299314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(453),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 2000m,
                            RegionId = 4,
                            Status = 0,
                            Title = "Магнитофон"
                        },
                        new
                        {
                            Id = 18,
                            Address = "299314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Примитивные стиральные машины представляли собой деревянный ящик с подвижной рамой. Первая стиральная машина, запущенная в серийное производство, была создана в 1907 году[источник не указан 109 дней] Уильямом Блекстоуном, у неё был ручной привод (есть также мнение, что первую сделал Натаниэл Бриггс (Nathaniel Briggs)). В Европе первые стиральные машины начали производить в Германии в 1900 г. Современные машины с электрическим приводом появились в 1904 году[1]. Механизация труда практически привела к исчезновению профессии прачки. В 1949 году в США появилась первая автоматическая стиральная машина.",
                            CategoryId = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(455),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 10000m,
                            RegionId = 5,
                            Status = 0,
                            Title = "Стиральная машина"
                        },
                        new
                        {
                            Id = 19,
                            Address = "299713 г. Керчь, ул. Куприна, 3",
                            Body = "Видеомагнитофо́н — устройство для записи телевизионного сигнала на магнитную ленту и его последующего воспроизведения[1][2]. От магнитофона отличается многократно увеличенной полосой записываемых частот и устройством лентопротяжного механизма[3]. Получаемая при помощи видеомагнитофона запись изображения и звука называется видеофонограммой[4][5]. Возможность записи высокочастотных и импульсных сигналов делает видеомагнитофон пригодным не только для видеозаписи, но и для других прикладных задач, связанных с регистрацией информации.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(456),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 40000m,
                            RegionId = 7,
                            Status = 0,
                            Title = "Видеомагнитофон"
                        },
                        new
                        {
                            Id = 20,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "Магнитофон (от магнит и греч. φωνή звук) — электромеханическое устройство, предназначенное для записи звуковой информации на магнитные носители и/или её воспроизведения. В качестве носителя используются материалы с магнитными свойствами: магнитная лента, проволока, магнитные манжеты, диски, барабаны и т. д.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(457),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 2000m,
                            RegionId = 8,
                            Status = 0,
                            Title = "Куплю магнитофон"
                        },
                        new
                        {
                            Id = 21,
                            Address = "299411 г. Москва, ул. Тургенева, 1",
                            Body = "Примитивные стиральные машины представляли собой деревянный ящик с подвижной рамой. Первая стиральная машина, запущенная в серийное производство, была создана в 1907 году[источник не указан 109 дней] Уильямом Блекстоуном, у неё был ручной привод (есть также мнение, что первую сделал Натаниэл Бриггс (Nathaniel Briggs)). В Европе первые стиральные машины начали производить в Германии в 1900 г. Современные машины с электрическим приводом появились в 1904 году[1]. Механизация труда практически привела к исчезновению профессии прачки. В 1949 году в США появилась первая автоматическая стиральная машина.",
                            CategoryId = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 608, DateTimeKind.Utc).AddTicks(459),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 2000m,
                            RegionId = 6,
                            Status = 0,
                            Title = "Стиральная машина"
                        });
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(3652),
                            IsDeleted = false,
                            Name = "Транспорт"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(3938),
                            IsDeleted = false,
                            Name = "Автомобили",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4196),
                            IsDeleted = false,
                            Name = "Мотоциклы и мототехника",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4199),
                            IsDeleted = false,
                            Name = "Грузовики и спецтехника",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4200),
                            IsDeleted = false,
                            Name = "Недвижимость"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4435),
                            IsDeleted = false,
                            Name = "Квартиры",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4437),
                            IsDeleted = false,
                            Name = "Комнаты",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4438),
                            IsDeleted = false,
                            Name = "Дома, дачи, коттеджи",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4439),
                            IsDeleted = false,
                            Name = "Электроника"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4440),
                            IsDeleted = false,
                            Name = "Аудио и видео",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4441),
                            IsDeleted = false,
                            Name = "Игры, приставки и программы",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4442),
                            IsDeleted = false,
                            Name = "Настольные компьютеры",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4443),
                            IsDeleted = false,
                            Name = "Ноутбуки",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4444),
                            IsDeleted = false,
                            Name = "Планшеты и электронные книги",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4445),
                            IsDeleted = false,
                            Name = "Телефоны",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4446),
                            IsDeleted = false,
                            Name = "Товары для компьютера",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 620, DateTimeKind.Utc).AddTicks(4447),
                            IsDeleted = false,
                            Name = "Фототехника",
                            ParentCategoryId = 9
                        });
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Region", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentRegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(7816),
                            Name = "Российская Федерация"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8110),
                            Name = "Центральный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8114),
                            Name = "Белгородская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8115),
                            Name = "Брянская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8116),
                            Name = "Владимирская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8117),
                            Name = "Воронежская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8118),
                            Name = "Ивановская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8119),
                            Name = "Калужская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8119),
                            Name = "Костромская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8120),
                            Name = "Курская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8121),
                            Name = "Липецкая область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8165),
                            Name = "Московская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8167),
                            Name = "Орловская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8167),
                            Name = "Рязанская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8168),
                            Name = "Смоленская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8169),
                            Name = "Тамбовская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8170),
                            Name = "Тверская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8172),
                            Name = "Тульская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8172),
                            Name = "Ярославская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8173),
                            Name = "г. Москва",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8174),
                            Name = "Северо-Западный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8175),
                            Name = "Республика Карелия",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8176),
                            Name = "Республика Коми",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8177),
                            Name = "Архангельская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8178),
                            Name = "в том числе Ненецкий автономный округ",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8179),
                            Name = "Вологодская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8180),
                            Name = "Калининградская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8181),
                            Name = "Ленинградская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8182),
                            Name = "Мурманская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8183),
                            Name = "Новгородская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8184),
                            Name = "Псковская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8185),
                            Name = "г. Санкт-Петербург",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8186),
                            Name = "Южный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8187),
                            Name = "Республика Адыгея",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8188),
                            Name = "Республика Дагестан",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8189),
                            Name = "Республика Ингушетия",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8190),
                            Name = "Кабардино-Балкарская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8191),
                            Name = "Республика Калмыкия",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8191),
                            Name = "Карачаево-Черкесская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8192),
                            Name = "Республика Северная Осетия - Алания",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8193),
                            Name = "Чеченская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8194),
                            Name = "Краснодарский край",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8195),
                            Name = "Ставропольский край",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8196),
                            Name = "Астраханская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8197),
                            Name = "Волгоградская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8198),
                            Name = "Ростовская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8199),
                            Name = "Приволжский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8200),
                            Name = "Республика Башкортостан",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8201),
                            Name = "Республика Марий Эл",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8202),
                            Name = "Республика Мордовия",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8203),
                            Name = "Республика Татарстан",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8204),
                            Name = "Удмуртская Республика",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8205),
                            Name = "Чувашская Республика",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8206),
                            Name = "Кировская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8207),
                            Name = "Нижегородская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8207),
                            Name = "Оренбургская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8208),
                            Name = "Пензенская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8209),
                            Name = "Пермская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8210),
                            Name = "в том числе Коми-Пермяцкий автономный округ",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8211),
                            Name = "Самарская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8212),
                            Name = "Саратовская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8213),
                            Name = "Ульяновская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8214),
                            Name = "Уральский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8215),
                            Name = "Курганская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8216),
                            Name = "Свердловская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8217),
                            Name = "Тюменская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8218),
                            Name = "в том числе Ханты-Мансийский автономный округ - Югра",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8219),
                            Name = "в том числе Ямало-Ненецкий автономный округ",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8220),
                            Name = "в том числе Челябинская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8221),
                            Name = "Сибирский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8222),
                            Name = "Республика Алтай",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8223),
                            Name = "Республика Бурятия",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8224),
                            Name = "Республика Тыва",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8224),
                            Name = "Республика Хакасия",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8225),
                            Name = "Алтайский край",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8226),
                            Name = "Красноярский край",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8227),
                            Name = "в том числе Таймырский (Долгано-Ненецкий) автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8228),
                            Name = "Эвенкийский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8229),
                            Name = "Иркутская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8230),
                            Name = "в том числе Усть-Ордынский Бурятский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8231),
                            Name = "Кемеровская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8232),
                            Name = "Новосибирская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8233),
                            Name = "Омская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8234),
                            Name = "Томская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8235),
                            Name = "Читинская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8236),
                            Name = "в том числе Агинский Бурятский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8236),
                            Name = "Дальневосточный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8237),
                            Name = "Республика Саха (Якутия)",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8238),
                            Name = "Приморский край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8239),
                            Name = "Хабаровский край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8240),
                            Name = "Амурская край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8241),
                            Name = "Камчатская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8242),
                            Name = "Корякский автономный округ",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8243),
                            Name = "Магаданская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8244),
                            Name = "Сахалинская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8245),
                            Name = "Еврейская автономная область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8246),
                            Name = "Чукотский автономный округ",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8247),
                            Name = "Севастополь",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2021, 11, 17, 23, 35, 37, 624, DateTimeKind.Utc).AddTicks(8247),
                            Name = "Крым",
                            ParentRegionId = 1
                        });
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Tag", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AdvertisementTag", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Advertisement", null)
                        .WithMany()
                        .HasForeignKey("AdvertisementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sev1.Advertisements.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Advertisement", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Category", "Category")
                        .WithMany("Advertisements")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Sev1.Advertisements.Domain.Region", "Region")
                        .WithMany("Advertisements")
                        .HasForeignKey("RegionId");

                    b.Navigation("Category");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Category", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Region", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Region", "ParentRegion")
                        .WithMany()
                        .HasForeignKey("ParentRegionId");

                    b.Navigation("ParentRegion");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Category", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Region", b =>
                {
                    b.Navigation("Advertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
