// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sev1.Advertisements.DataAccess;

namespace Advertisements.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211114162610_RegionsWereAdded")]
    partial class RegionsWereAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertisementTag", b =>
                {
                    b.Property<int>("AdvertisementsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("AdvertisementsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagAdvertisement");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Advertisement", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(3951),
                            IsDeleted = false,
                            Name = "Транспорт"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4449),
                            IsDeleted = false,
                            Name = "Автомобили",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4682),
                            IsDeleted = false,
                            Name = "Мотоциклы и мототехника",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4684),
                            IsDeleted = false,
                            Name = "Грузовики и спецтехника",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4686),
                            IsDeleted = false,
                            Name = "Недвижимость"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4912),
                            IsDeleted = false,
                            Name = "Квартиры",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4914),
                            IsDeleted = false,
                            Name = "Комнаты",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4915),
                            IsDeleted = false,
                            Name = "Дома, дачи, коттеджи",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4916),
                            IsDeleted = false,
                            Name = "Электроника"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4917),
                            IsDeleted = false,
                            Name = "Аудио и видео",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4918),
                            IsDeleted = false,
                            Name = "Игры, приставки и программы",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4919),
                            IsDeleted = false,
                            Name = "Настольные компьютеры",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4920),
                            IsDeleted = false,
                            Name = "Ноутбуки",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4960),
                            IsDeleted = false,
                            Name = "Планшеты и электронные книги",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4962),
                            IsDeleted = false,
                            Name = "Телефоны",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4963),
                            IsDeleted = false,
                            Name = "Товары для компьютера",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 639, DateTimeKind.Utc).AddTicks(4964),
                            IsDeleted = false,
                            Name = "Фототехника",
                            ParentCategoryId = 9
                        });
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Region", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentRegionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(7999),
                            IsDeleted = false,
                            Name = "Российская Федерация"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8283),
                            IsDeleted = false,
                            Name = "Центральный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8286),
                            IsDeleted = false,
                            Name = "Белгородская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8287),
                            IsDeleted = false,
                            Name = "Брянская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8288),
                            IsDeleted = false,
                            Name = "Владимирская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8289),
                            IsDeleted = false,
                            Name = "Воронежская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8291),
                            IsDeleted = false,
                            Name = "Ивановская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8292),
                            IsDeleted = false,
                            Name = "Калужская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8293),
                            IsDeleted = false,
                            Name = "Костромская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8294),
                            IsDeleted = false,
                            Name = "Курская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8295),
                            IsDeleted = false,
                            Name = "Липецкая область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8296),
                            IsDeleted = false,
                            Name = "Московская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8297),
                            IsDeleted = false,
                            Name = "Орловская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8298),
                            IsDeleted = false,
                            Name = "Рязанская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8299),
                            IsDeleted = false,
                            Name = "Смоленская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8300),
                            IsDeleted = false,
                            Name = "Тамбовская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8301),
                            IsDeleted = false,
                            Name = "Тверская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8302),
                            IsDeleted = false,
                            Name = "Тульская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8303),
                            IsDeleted = false,
                            Name = "Ярославская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8304),
                            IsDeleted = false,
                            Name = "г. Москва",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8305),
                            IsDeleted = false,
                            Name = "Северо-Западный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8306),
                            IsDeleted = false,
                            Name = "Республика Карелия",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8307),
                            IsDeleted = false,
                            Name = "Республика Коми",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8308),
                            IsDeleted = false,
                            Name = "Архангельская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8309),
                            IsDeleted = false,
                            Name = "в том числе Ненецкий автономный округ",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8368),
                            IsDeleted = false,
                            Name = "Вологодская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8370),
                            IsDeleted = false,
                            Name = "Калининградская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8371),
                            IsDeleted = false,
                            Name = "Ленинградская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8372),
                            IsDeleted = false,
                            Name = "Мурманская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8373),
                            IsDeleted = false,
                            Name = "Новгородская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8374),
                            IsDeleted = false,
                            Name = "Псковская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8375),
                            IsDeleted = false,
                            Name = "г. Санкт-Петербург",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8376),
                            IsDeleted = false,
                            Name = "Южный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8377),
                            IsDeleted = false,
                            Name = "Республика Адыгея",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8378),
                            IsDeleted = false,
                            Name = "Республика Дагестан",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8379),
                            IsDeleted = false,
                            Name = "Республика Ингушетия",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8380),
                            IsDeleted = false,
                            Name = "Кабардино-Балкарская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8381),
                            IsDeleted = false,
                            Name = "Республика Калмыкия",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8382),
                            IsDeleted = false,
                            Name = "Карачаево-Черкесская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8383),
                            IsDeleted = false,
                            Name = "Республика Северная Осетия - Алания",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8384),
                            IsDeleted = false,
                            Name = "Чеченская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8385),
                            IsDeleted = false,
                            Name = "Краснодарский край",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8386),
                            IsDeleted = false,
                            Name = "Ставропольский край",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8387),
                            IsDeleted = false,
                            Name = "Астраханская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8388),
                            IsDeleted = false,
                            Name = "Волгоградская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8389),
                            IsDeleted = false,
                            Name = "Ростовская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8390),
                            IsDeleted = false,
                            Name = "Приволжский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8391),
                            IsDeleted = false,
                            Name = "Республика Башкортостан",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8392),
                            IsDeleted = false,
                            Name = "Республика Марий Эл",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8393),
                            IsDeleted = false,
                            Name = "Республика Мордовия",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8394),
                            IsDeleted = false,
                            Name = "Республика Татарстан",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8395),
                            IsDeleted = false,
                            Name = "Удмуртская Республика",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8396),
                            IsDeleted = false,
                            Name = "Чувашская Республика",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8397),
                            IsDeleted = false,
                            Name = "Кировская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8398),
                            IsDeleted = false,
                            Name = "Нижегородская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8400),
                            IsDeleted = false,
                            Name = "Оренбургская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8401),
                            IsDeleted = false,
                            Name = "Пензенская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8401),
                            IsDeleted = false,
                            Name = "Пермская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8402),
                            IsDeleted = false,
                            Name = "в том числе Коми-Пермяцкий автономный округ",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8403),
                            IsDeleted = false,
                            Name = "Самарская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8404),
                            IsDeleted = false,
                            Name = "Саратовская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8405),
                            IsDeleted = false,
                            Name = "Ульяновская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8407),
                            IsDeleted = false,
                            Name = "Уральский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8408),
                            IsDeleted = false,
                            Name = "Курганская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8409),
                            IsDeleted = false,
                            Name = "Свердловская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8410),
                            IsDeleted = false,
                            Name = "Тюменская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8411),
                            IsDeleted = false,
                            Name = "в том числе Ханты-Мансийский автономный округ - Югра",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8412),
                            IsDeleted = false,
                            Name = "в том числе Ямало-Ненецкий автономный округ",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8413),
                            IsDeleted = false,
                            Name = "в том числе Челябинская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8414),
                            IsDeleted = false,
                            Name = "Сибирский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8463),
                            IsDeleted = false,
                            Name = "Республика Алтай",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8464),
                            IsDeleted = false,
                            Name = "Республика Бурятия",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8465),
                            IsDeleted = false,
                            Name = "Республика Тыва",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8466),
                            IsDeleted = false,
                            Name = "Республика Хакасия",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8467),
                            IsDeleted = false,
                            Name = "Алтайский край",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8468),
                            IsDeleted = false,
                            Name = "Красноярский край",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8469),
                            IsDeleted = false,
                            Name = "в том числе Таймырский (Долгано-Ненецкий) автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8470),
                            IsDeleted = false,
                            Name = "Эвенкийский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8471),
                            IsDeleted = false,
                            Name = "Иркутская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8472),
                            IsDeleted = false,
                            Name = "в том числе Усть-Ордынский Бурятский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8473),
                            IsDeleted = false,
                            Name = "Кемеровская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8474),
                            IsDeleted = false,
                            Name = "Новосибирская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8475),
                            IsDeleted = false,
                            Name = "Омская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8477),
                            IsDeleted = false,
                            Name = "Томская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8478),
                            IsDeleted = false,
                            Name = "Читинская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8478),
                            IsDeleted = false,
                            Name = "в том числе Агинский Бурятский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8479),
                            IsDeleted = false,
                            Name = "Дальневосточный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8480),
                            IsDeleted = false,
                            Name = "Республика Саха (Якутия)",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8481),
                            IsDeleted = false,
                            Name = "Приморский край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8483),
                            IsDeleted = false,
                            Name = "Хабаровский край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8484),
                            IsDeleted = false,
                            Name = "Амурская край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8484),
                            IsDeleted = false,
                            Name = "Камчатская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8485),
                            IsDeleted = false,
                            Name = "Корякский автономный округ",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8486),
                            IsDeleted = false,
                            Name = "Магаданская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8488),
                            IsDeleted = false,
                            Name = "Сахалинская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8489),
                            IsDeleted = false,
                            Name = "Еврейская автономная область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8490),
                            IsDeleted = false,
                            Name = "Чукотский автономный округ",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8491),
                            IsDeleted = false,
                            Name = "Севастополь",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2021, 11, 14, 16, 26, 9, 644, DateTimeKind.Utc).AddTicks(8492),
                            IsDeleted = false,
                            Name = "Крым",
                            ParentRegionId = 1
                        });
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Tag", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AdvertisementTag", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Advertisement", null)
                        .WithMany()
                        .HasForeignKey("AdvertisementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sev1.Advertisements.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Advertisement", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Category", "Category")
                        .WithMany("Advertisements")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Sev1.Advertisements.Domain.Region", null)
                        .WithMany("Advertisements")
                        .HasForeignKey("RegionId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Category", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Region", b =>
                {
                    b.HasOne("Sev1.Advertisements.Domain.Region", "ParentRegion")
                        .WithMany()
                        .HasForeignKey("ParentRegionId");

                    b.Navigation("ParentRegion");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Category", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("Sev1.Advertisements.Domain.Region", b =>
                {
                    b.Navigation("Advertisements");
                });
#pragma warning restore 612, 618
        }
    }
}
